---
title: "Final Project"
author: "Hui-Chen Betty Liu"
date: "December 6, 2019"
output: github_document
---

### Problem Statement

> Is there a significant difference in income between men and women? Does the difference vary depending on other factors (e.g., education, marital status, criminal history, drug use, childhood household factors, profession, etc.)?

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
# This section is for loading packages

library(tidyverse)
library(knitr)
library(dplyr)
options(scipen = 4)
```


```{r}
# This section is for loading data and some basic data cleaning

nlsydata <- read_csv("http://www.andrew.cmu.edu/user/achoulde/94842/final_project/nlsy79/nlsy79_income.csv")

# Rename all the variables so that they are descriptive.

nlsydata1 <- nlsydata %>% 
  rename(version = A0002500, 
         respondent.id = R0000100,
         us.born = R0000700, 
         usborn.south = R0001010, 
         multilingual = R0001100, 
         language = R0001200, 
         age14.south = R0001610, 
         age14.urban = R0001800, 
         religion = R0010300, 
         education1979 = R0023500, 
         veteran = R0029100, 
         fa.womenathome = R0153800, 
         fa.notimetowork = R0153900, 
         fa.proworkwife = R0154000, 
         fa.badchildren = R0154100, 
         fa.genderrole = R0154300, 
         fa.menhousework = R0154400, 
         fa.happytradrole = R0154500, 
         ideal.occupation = R0170100, 
         schoolin5years = R0171800, 
         race = R0214700, 
         gender = R0214800, 
         marital.status1979 = R0217501, 
         familysize1979 = R0217502, 
         poverty1979 = R0217910, 
         police.frisk = R0306700, 
         age.1stfrisk= R0307000, 
         crime.charge = R0307100, 
         age.1stalcohol = R1021700, 
         marijuana = R1395100, 
         age.1stmarijuana = R1395400, 
         income1990 = R3279401, 
         poverty1990 = R3400800, 
         education1990 = R3401501, 
         jobs.held1990 = R3403500, 
         nonbio.children = R3407700, 
         age.nonbiokid = R3407800, 
         cocaine1990 = R6430800, 
         age.1stcocaine = R6430900, 
         industry2000 = R6591300, 
         occupation2000 = R6592900, 
         spouse.occupation2000 = R6738700, 
         spouse.workhours2000 = R6749800, 
         number.children = R6839600, 
         income2000 = R6909701, 
         familysize2000 = R7006400, 
         household.income1999 = R7006500, 
         poverty2000 = R7006600, 
         maritalc.status2000 = R7006900, 
         marital.status2000 = R7007000, 
         months.marryto1stkid= R9909700, 
         partner.birthyear = T3206901, 
         industry2012 = T3308200, 
         occupation2012 = T3308700, 
         spouse.occupation2012 = T3495400, 
         spouse.workhours2012 = T3506500, 
         alcohol.dailyconsume = T3976400, 
         income2012= T3977400, 
         income2012x = T3977500, 
         income2012y= T3977600, 
         spouse.income2012 = T3987600, 
         spouse.income2012r= T3987800, 
         familysize2012= T4112200, 
         us.region = T4112700, 
         education2012 = T4113000, 
         urban.residence = T4114600, 
         jobs.held2012 = T4114900)
```

```{r}
# Clean income data in income2012 by making a new data frame that contains only rows that have 0 or greater values in the outcome variable, since negative numbers means NA in this context.

nlsydata2 <- mutate(filter(nlsydata1, 
       income2012 >= 0) %>%
  select(everything()))

#After cleaning, reordering, recoding all variable, a new version of data was created

nlsydata3 <- nlsydata2

```

```{r}

# Drop columns that are not meaningful


# Drop version because it's the same (445) for every respondent
nlsydata3 <- subset(nlsydata3, select = -c(version))

#Drop age14.south because the interpretation is unclear. Not sure if "Yes" means reside in the south at age 14 or not.
nlsydata3 <- subset(nlsydata3, select = -c(age14.south))

# Drop income2012x because the information is already captured by income2012 and because it only has 64 data points
nlsydata3 <- subset(nlsydata3, select = -c(income2012x))

# Drop income2012y because the information is already captured by income2012 and because it only has 64 data points
nlsydata3 <- subset(nlsydata3, select = -c(income2012y))

# Drop spouse.income2012r because the information is already captured by spouse.income2012 and because it only has 54 data points
nlsydata3 <- subset(nlsydata3, select = -c(spouse.income2012r))



```

```{r}
#clean each column

#For factor variables, take non responses and code it as NA

nlsydata3$us.born[nlsydata3$us.born < 0] <- NA

nlsydata3$usborn.south[nlsydata3$usborn.south < 0] <- NA

nlsydata3$multilingual[nlsydata3$multilingual < 0] <- NA

nlsydata3$language[nlsydata3$language < 0] <- NA

nlsydata3$age14.urban[nlsydata3$age14.urban < 0] <- NA

nlsydata3$religion[nlsydata3$religion < 0] <- NA

nlsydata3$education1979[nlsydata3$education1979 < 0] <- NA

nlsydata3$veteran[nlsydata3$veteran < 0] <- NA

nlsydata3$fa.womenathome[nlsydata3$fa.womenathome < 0] <- NA

nlsydata3$fa.notimetowork[nlsydata3$fa.notimetowork < 0] <- NA

nlsydata3$fa.proworkwife[nlsydata3$fa.proworkwife < 0] <- NA

nlsydata3$fa.badchildren[nlsydata3$fa.badchildren < 0] <- NA

nlsydata3$fa.genderrole[nlsydata3$fa.genderrole < 0] <- NA

nlsydata3$fa.menhousework[nlsydata3$fa.menhousework < 0] <- NA

nlsydata3$fa.happytradrole[nlsydata3$fa.happytradrole < 0] <- NA

nlsydata3$ideal.occupation[nlsydata3$ideal.occupation <= 0] <- NA

nlsydata3$ideal.occupation[nlsydata3$ideal.occupation == 995] <- NA

nlsydata3$schoolin5years[nlsydata3$schoolin5years < 0] <- NA

nlsydata3$marital.status1979[nlsydata3$marital.status1979 < 0] <- NA

nlsydata3$police.frisk[nlsydata3$police.frisk < 0] <- NA

nlsydata3$age.1stfrisk[nlsydata3$age.1stfrisk < 0] <- NA

nlsydata3$crime.charge[nlsydata3$crime.charge < 0] <- NA

nlsydata3$age.1stalcohol[nlsydata3$age.1stalcohol < 0] <- NA

nlsydata3$marijuana[nlsydata3$marijuana < 0] <- NA

nlsydata3$age.1stmarijuana[nlsydata3$age.1stmarijuana < 0] <- NA

nlsydata3$income1990[nlsydata3$income1990 < 0] <- NA

nlsydata3$poverty1990[nlsydata3$poverty1990 < 0] <- NA

nlsydata3$education1990[nlsydata3$education1990 < 0] <- NA

nlsydata3$jobs.held1990[nlsydata3$jobs.held1990 < 0] <- NA

nlsydata3$nonbio.children[nlsydata3$nonbio.children < 0] <- NA

nlsydata3$age.nonbiokid[nlsydata3$age.nonbiokid < 0] <- NA

nlsydata3$cocaine1990[nlsydata3$cocaine1990 == -5] <- NA

nlsydata3$cocaine1990[nlsydata3$cocaine1990 == -4] <- NA

nlsydata3$age.1stcocaine[nlsydata3$age.1stcocaine < 0] <- NA

nlsydata3$industry2000[nlsydata3$industry2000 <= 0] <- NA

nlsydata3$occupation2000[nlsydata3$occupation2000 <= 2] <- NA

nlsydata3$occupation2000[nlsydata3$occupation2000 >= 890] <- NA

nlsydata3$spouse.occupation2000[nlsydata3$spouse.occupation2000 < 0] <- NA

nlsydata3$spouse.workhours2000[nlsydata3$spouse.workhours2000 < 0] <- NA

nlsydata3$number.children[nlsydata3$number.children < 0] <- NA

nlsydata3$income2000[nlsydata3$income2000 < 0] <- NA

nlsydata3$familysize2000[nlsydata3$familysize2000 < 0] <- NA

nlsydata3$household.income1999[nlsydata3$household.income1999 < 0] <- NA

nlsydata3$poverty2000[nlsydata3$poverty2000 < 0] <- NA

nlsydata3$maritalc.status2000[nlsydata3$maritalc.status2000 < 0] <- NA

nlsydata3$marital.status2000[nlsydata3$marital.status2000 < 0] <- NA

nlsydata3$months.marryto1stkid[nlsydata3$months.marryto1stkid == -999] <- NA

nlsydata3$partner.birthyear[nlsydata3$partner.birthyear < 0] <- NA

nlsydata3$industry2012[nlsydata3$industry2012 < 0] <- NA

nlsydata3$industry2012[nlsydata3$industry2012 == 9950] <- NA

nlsydata3$industry2012[nlsydata3$industry2012 == 9990] <- NA

nlsydata3$occupation2012[nlsydata3$occupation2012 < 0] <- NA

nlsydata3$occupation2012[nlsydata3$occupation2012 == 9950] <- NA

nlsydata3$occupation2012[nlsydata3$occupation2012 == 9990] <- NA

nlsydata3$spouse.occupation2012[nlsydata3$spouse.occupation2012 < 0] <- NA

nlsydata3$spouse.occupation2012[nlsydata3$spouse.occupation2012 == 9950] <- NA

nlsydata3$spouse.occupation2012[nlsydata3$spouse.occupation2012 == 9990] <- NA

nlsydata3$spouse.workhours2012[nlsydata3$spouse.workhours2012 < 0] <- NA

nlsydata3$alcohol.dailyconsume[nlsydata3$alcohol.dailyconsume < 0] <- NA

nlsydata3$spouse.income2012[nlsydata3$spouse.income2012 < 0] <- NA

nlsydata3$familysize2012[nlsydata3$familysize2012 < 0] <- NA

nlsydata3$us.region[nlsydata3$us.region < 0] <- NA

nlsydata3$education2012[nlsydata3$education2012 < 0] <- NA

nlsydata3$urban.residence[nlsydata3$urban.residence < 0] <- NA

nlsydata3$jobs.held2012[nlsydata3$jobs.held2012 < 0] <- NA


```

```{r}
# Transform and relabel factor variables

#recoded religion to create a new variable that is Christian/not Christian
#recoded education to create a new variable that captures education completion levels (elementary, middle, high school, college)
# Recode

nlsydata3 <- mutate(nlsydata3, 
                    us.born = recode_factor(us.born, 
                    `1` = "US", 
                    `2` = "Non-US"),
                    usborn.south = recode_factor(usborn.south, 
                    `0` = "Non-South", 
                    `1` = "South"), 
                    multilingual = recode_factor(multilingual, 
                    `0` = "English", 
                    `1` = "Multilingual"), 
                    language = recode_factor(language, 
                    `1` = "Spanish", 
                    `2` = "French", 
                    `3` = "German", 
                    `4` = "Other"), 
                    age14.urban = recode_factor(age14.urban, 
                    `1` = "City", 
                    `2` = "Country", 
                    `3` = "Farm"), 
                    religion = recode_factor(religion, 
                    `0` = "No religion",
                    `1` = "Protestant", 
                    `2` = "Baptist", 
                    `3` = "Episcopalian", 
                    `4` = "Lutheran", 
                    `5` = "Methodist", 
                    `6` = "Presbyterian", 
                    `7` = "Roman Catholic", 
                    `8` = "Jewish", 
                    `9` = "Other"), 
                    christian = recode_factor(religion, 
                    `No religion` = "Not Christian",
                    `Jewish` = "Not Christian", 
                    `Other` = "Not Christian",
                    `Protestant` = "Christian", 
                    `Baptist` = "Christian", 
                    `Episcopalian` = "Christian", 
                    `Lutheran` = "Christian", 
                    `Methodist` = "Christian", 
                    `Presbyterian` = "Christian", 
                    `Roman Catholic` = "Roman Catholic"), 
                    education1979 = recode_factor(education1979,
                    `1` = "1st grade", 
                    `2` = "2nd grade",
                    `3` = "3rd grade", 
                    `4` = "4th grade", 
                    `5` = "5th grade", 
                    `6` = "6th grade", 
                    `7` = "7th grade", 
                    `8` = "8th grade", 
                    `9` = "9th grade", 
                    `10` = "10th grade", 
                    `11` = "11th grade", 
                    `12` = "12th grade",
                    `13` = "1st year college", 
                    `14` = "2nd year college", 
                    `15` = "3rd year college", 
                    `16` = "4th year college", 
                    `17` = "5th year college", 
                    `18` = "6th+ year college"), 
                    exp.edu1979 = recode_factor(education1979, 
                    `1st grade` = "Some elementary", 
                    `2nd grade` = "Some elementary",
                    `3rd grade` = "Some elementary", 
                    `4th grade` = "Some elementary", 
                    `5th grade` = "Complete elementary", 
                    `6th grade` = "Some middle school", 
                    `7th grdade` = "Some middle school", 
                    `8th grade` = "Complete middle school", 
                    `9th grade` = "Some high school", 
                    `10th grade` = "Some high school", 
                    `11th grade` = "Some high school", 
                    `12th grade` = "Complete high school",
                    `1st year college` = "Some college", 
                    `2nd year college` = "Some college", 
                    `3rd year college` = "Some college", 
                    `4th year college` = "Complete college", 
                    `5th year college` = "Complete college", 
                    `6th+ year college` = "Complete college"), 
                    veteran = recode_factor(veteran, 
                    `0` = "Not veteran", 
                    `1` = "Veteran"), 
                    fa.proworkwife = recode_factor(fa.proworkwife, 
                    `4` = 1, 
                    `3` = 2, 
                    `2` = 3, 
                    `1` = 4), 
                    fa.menhousework = recode_factor(fa.menhousework, 
                    `4` = 1, 
                    `3` = 2, 
                    `2` = 3, 
                    `1` = 4), 
                    schoolin5years = recode_factor(schoolin5years, 
                    `0` = "No", 
                    `1` = "Yes"), 
                    marital.status1979 = recode_factor(marital.status1979, 
                    `0` = "Never Married", 
                    `1` = "Married", 
                    `2` = "Separated", 
                    `3` = "Divorced", 
                    `5` = "Remarried", 
                    `6` = "Widowed"), 
                    poverty1979 = recode_factor(poverty1979, 
                    `0` = "Not in Poverty", 
                    `1` = "Poverty"), 
                    police.frisk = recode_factor(police.frisk, 
                    `0` = "Not Frisked",
                    `1` = "Frisked"), 
                    crime.charge = recode_factor(crime.charge, 
                    `0` = "Never charged",
                    `1` = "Charged"), 
                    poverty1990 = recode_factor(poverty1990, 
                    `0` = "Not in Poverty", 
                    `1` = "Poverty"), 
                    education1990 = recode_factor(education1990,
                    `1` = "1st grade", 
                    `2` = "2nd grade",
                    `3` = "3rd grade", 
                    `4` = "4th grade", 
                    `5` = "5th grade", 
                    `6` = "6th grade", 
                    `7` = "7th grade", 
                    `8` = "8th grade", 
                    `9` = "9th grade", 
                    `10` = "10th grade", 
                    `11` = "11th grade", 
                    `12` = "12th grade",
                    `13` = "1st year college", 
                    `14` = "2nd year college", 
                    `15` = "3rd year college", 
                    `16` = "4th year college", 
                    `17` = "5th year college", 
                    `18` = "6th year college", 
                    `19` = "7th year college", 
                    `20` = "8th + year college"), 
                    edu.completedin1990 = recode_factor(education1990, 
                    `1st grade` = "Some elementary", 
                    `2nd grade` = "Some elementary",
                    `3rd grade` = "Some elementary", 
                    `4th grade` = "Some elementary", 
                    `5th grade` = "Complete elementary", 
                    `6th grade` = "Some middle school", 
                    `7th grdade` = "Some middle school", 
                    `8th grade` = "Complete middle school", 
                    `9th grade` = "Some high school", 
                    `10th grade` = "Some high school", 
                    `11th grade` = "Some high school", 
                    `12th grade` = "Complete high school",
                    `1st year college` = "Some college", 
                    `2nd year college` = "Some college", 
                    `3rd year college` = "Some college", 
                    `4th year college` = "Complete college", 
                    `5th year college` = "Complete college", 
                    `6th year college` = "Complete college", 
                    `7th year college` = "Complete college", 
                    `8th year college` = "Complete college"), 
                    cocaine1990 = recode_factor(cocaine1990, 
                    `0` = "Never", 
                    `1` = "1-2 times", 
                    `2` = "3-5 times", 
                    `3` = "6-10 times", 
                    `4` = "11-49 times", 
                    `5` = "50-99 times", 
                    `6` = "100 or more times", 
                    `-1` = "Refuse to answer", 
                    `-2` = "I don't know"), 
                    poverty2000 = recode_factor(poverty2000, 
                    `0` = "Not in Poverty", 
                    `1` = "Poverty"), 
                    maritalc.status2000 = recode_factor(maritalc.status2000, 
                    `1` = "Never Married", 
                    `2` = "Married, Spouse Present", 
                    `3` = "Other"), 
                    marital.status2000 = recode_factor(marital.status2000, 
                    `0` = "Never Married", 
                    `1` = "Married", 
                    `2` = "Separated", 
                    `3` = "Divorced", 
                    `6` = "Widowed"), 
                    us.region = recode_factor(us.region, 
                    `3` = "South", 
                    `1` = "Northeast", 
                    `2` = "North Central", 
                    `4` = "West"), 
                    education2012 = recode_factor(education2012,
                    `0` = "No education",
                    `1` = "1st grade",
                    `2` = "2nd grade",
                    `3` = "3rd grade", 
                    `4` = "4th grade", 
                    `5` = "5th grade", 
                    `6` = "6th grade", 
                    `7` = "7th grade", 
                    `8` = "8th grade", 
                    `9` = "9th grade", 
                    `10` = "10th grade", 
                    `11` = "11th grade", 
                    `12` = "12th grade",
                    `13` = "1st year college", 
                    `14` = "2nd year college", 
                    `15` = "3rd year college", 
                    `16` = "4th year college", 
                    `17` = "5th year college", 
                    `18` = "6th year college", 
                    `19` = "7th year college", 
                    `20` = "8th + year college"), 
                    edu.completedin2012 = recode_factor(education2012, 
                    `1st grade` = "Some elementary", 
                    `2nd grade` = "Some elementary",
                    `3rd grade` = "Some elementary", 
                    `4th grade` = "Some elementary", 
                    `5th grade` = "Complete elementary", 
                    `6th grade` = "Some middle school", 
                    `7th grdade` = "Some middle school", 
                    `8th grade` = "Complete middle school", 
                    `9th grade` = "Some high school", 
                    `10th grade` = "Some high school", 
                    `11th grade` = "Some high school", 
                    `12th grade` = "Complete high school",
                    `1st year college` = "Some college", 
                    `2nd year college` = "Some college", 
                    `3rd year college` = "Some college", 
                    `4th year college` = "Complete college", 
                    `5th year college` = "Complete college", 
                    `6th year college` = "Complete college", 
                    `7th year college` = "Complete college", 
                    `8th year college` = "Complete college"), 
                    urban.residence = recode_factor(urban.residence, 
                    `1` = "Urban", 
                    `0` = "Rural", 
                    `2` = "Unknown"))
```

```{r}
#created new variable age.spouse to capture spouse's age using values from partner.birthyear

nlsydata3 <- nlsydata3 %>% 
   mutate(age.spouse = 2012 - partner.birthyear)
```


```{r}
# recoded ideal.occupation as factor variable with category names
# recoded industry2020 as a factor variable with industry names
# recoded occupation2020 as a factor variable with occupation names

nlsydata3 <- nlsydata3 %>% 
   mutate(ideal.occupation = factor(case_when(
    .$ideal.occupation >= 1 & .$ideal.occupation <= 195 ~ "Technical",
    .$ideal.occupation >= 201 & .$ideal.occupation <= 245 ~ "Manager", 
    .$ideal.occupation >= 260 & .$ideal.occupation <= 285 ~ "Sales",
    .$ideal.occupation >= 301 & .$ideal.occupation <= 395 ~ "Clerical",
    .$ideal.occupation >= 401 & .$ideal.occupation <= 575 ~ "Craftsman",
    .$ideal.occupation >= 580 & .$ideal.occupation <= 590 ~ "Military",
    .$ideal.occupation >= 601 & .$ideal.occupation <= 715 ~ "Operative",
    .$ideal.occupation >= 740 & .$ideal.occupation <= 785 ~ "Laborer",
    .$ideal.occupation >= 801 & .$ideal.occupation <= 802 ~ "Farm Manager",
    .$ideal.occupation >= 821 & .$ideal.occupation <= 824 ~ "Farm Laborer",
    .$ideal.occupation >= 901 & .$ideal.occupation <= 965 ~ "Service",
    .$ideal.occupation >= 980 & .$ideal.occupation <= 984 ~ "Private Household")))

nlsydata3 <- nlsydata3 %>% 
   mutate(industry2000 = factor(case_when(
    .$industry2000 >= 17 & .$industry2000 <= 28 ~ "Agriculture & Fisheries",
    .$industry2000 >= 47 & .$industry2000 <= 57 ~ "Mining", 
    .$industry2000 >= 67 & .$industry2000 <= 77 ~ "Construction",
    .$industry2000 >= 107 & .$industry2000 <= 398 ~ "Manufacturing",
    .$industry2000 >= 407 & .$industry2000 <= 479 ~ "Transportation & Public Utilities",
    .$industry2000 >= 507 & .$industry2000 <= 698 ~ "Wholesale & Retail Trade",
    .$industry2000 >= 707 & .$industry2000 <= 718 ~ "Finance & Real Estate",
    .$industry2000 >= 727 & .$industry2000 <= 759 ~ "Repair Services",
    .$industry2000 >= 769 & .$industry2000 <= 798 ~ "Personal Services",
    .$industry2000 >= 807 & .$industry2000 <= 809 ~ "Entertainment & Recreation Services",
    .$industry2000 >= 828 & .$industry2000 <= 897 ~ "Professional Services",
    .$industry2000 >= 907 & .$industry2000 <= 937 ~ "Public Administration")))

nlsydata3 <- nlsydata3 %>% 
   mutate(occupation2000 = factor(case_when(
    .$occupation2000 >= 3 & .$occupation2000 <= 199 ~ "Managerial & Professional",
    .$occupation2000 >= 203 & .$occupation2000 <= 235 ~ "Technical", 
    .$occupation2000 >= 243 & .$occupation2000 <= 285 ~ "Sales",
    .$occupation2000 >= 303 & .$occupation2000 <= 389 ~ "Clerical & Administrative Support",
    .$occupation2000 >= 403 & .$occupation2000 <= 469 ~ "Service",
    .$occupation2000 >= 473 & .$occupation2000 <= 499 ~ "Farming & Fishing",
    .$occupation2000 >= 503 & .$occupation2000 <= 699 ~ "Craft & Repair Services",
    .$occupation2000 >= 703 & .$occupation2000 <= 799 ~ "Operators - Machine, Assemblers, Inspectors",
    .$occupation2000 >= 803 & .$occupation2000 <= 859 ~ "Operators - Transportation, Material Moving",
    .$occupation2000 >= 863 & .$occupation2000 <= 889 ~ "Operators - Handlers, Helpers, Laborers")))

nlsydata3 <- nlsydata3 %>% 
   mutate(spouse.occupation2000 = factor(case_when(
    .$spouse.occupation2000 >= 1 & .$spouse.occupation2000 <= 195 ~ "Technical",
    .$spouse.occupation2000 >= 201 & .$spouse.occupation2000 <= 245 ~ "Manager", 
    .$spouse.occupation2000 >= 260 & .$spouse.occupation2000 <= 285 ~ "Sales",
    .$spouse.occupation2000 >= 301 & .$spouse.occupation2000 <= 395 ~ "Clerical",
    .$spouse.occupation2000 >= 401 & .$spouse.occupation2000 <= 575 ~ "Craftsman",
    .$spouse.occupation2000 >= 580 & .$spouse.occupation2000 <= 590 ~ "Military",
    .$spouse.occupation2000 >= 601 & .$spouse.occupation2000 <= 715 ~ "Operative",
    .$spouse.occupation2000 >= 740 & .$spouse.occupation2000 <= 785 ~ "Laborer",
    .$spouse.occupation2000 >= 801 & .$spouse.occupation2000 <= 802 ~ "Farm Manager",
    .$spouse.occupation2000 >= 821 & .$spouse.occupation2000 <= 824 ~ "Farm Laborer",
    .$spouse.occupation2000 >= 901 & .$spouse.occupation2000 <= 965 ~ "Service",
    .$spouse.occupation2000 >= 980 & .$spouse.occupation2000 <= 984 ~ "Private Household")))

nlsydata3 <- nlsydata3 %>% 
   mutate(months.marryto1stkid = factor(case_when(
    .$months.marryto1stkid == 0 ~ "Same month", 
    .$months.marryto1stkid >= 1 & .$months.marryto1stkid <= 11 ~ "Within a year",
    .$months.marryto1stkid >= 12 & .$months.marryto1stkid <= 23 ~ "2 years", 
    .$months.marryto1stkid >= 24 & .$months.marryto1stkid <= 35 ~ "3 years",
    .$months.marryto1stkid >= 36 & .$months.marryto1stkid <= 47 ~ "4 years",
    .$months.marryto1stkid >= 48 & .$months.marryto1stkid <= 59 ~ "5 years",
    .$months.marryto1stkid >= 60 & .$months.marryto1stkid <= 71 ~ "6 years",
    .$months.marryto1stkid >= 72 & .$months.marryto1stkid <= 83 ~ "7 years",
    .$months.marryto1stkid >= 84 & .$months.marryto1stkid <= 95 ~ "8 years",
    .$months.marryto1stkid >= 96 & .$months.marryto1stkid <= 107 ~ "9 years",
    .$spouse.occupation2000 >= 108 & .$months.marryto1stkid <= 119 ~ "10 years",
    .$months.marryto1stkid >= 120 & .$months.marryto1stkid <= 131 ~ "11 years",
    .$months.marryto1stkid >= 132 & .$months.marryto1stkid <= 143 ~ "12 years", 
    .$months.marryto1stkid >= 144 & .$months.marryto1stkid <= 999 ~ "More than 12 years", 
    .$months.marryto1stkid == -997 ~ "Never married", 
    .$months.marryto1stkid == -998 ~ "No children")))


nlsydata3 <- nlsydata3 %>% 
   mutate(industry2012 = factor(case_when(
    .$industry2012 >= 170 & .$industry2012 <= 290 ~ "Agriculture & Fisheries",
    .$industry2012 >= 370 & .$industry2012 <= 490 ~ "Mining", 
    .$industry2012 >= 570 & .$industry2012 <= 690 ~ "Utilities",
    .$industry2012 == 770 ~ "Construction",
    .$industry2012 >= 1070 & .$industry2012 <= 3990 ~ "Manufacturing",
    .$industry2012 >= 4070 & .$industry2012 <= 4590 ~ "Wholesale Trade",
    .$industry2012 >= 4670 & .$industry2012 <= 5790 ~ "Retail Trade",
    .$industry2012 >= 6070 & .$industry2012 <= 6390 ~ "Transportation & Warehousing", 
    .$industry2012 >= 6470 & .$industry2012 <= 6780 ~ "Information",
    .$industry2012 >= 6870 & .$industry2012 <= 6990 ~ "Finance & Insurance",
    .$industry2012 >= 7070 & .$industry2012 <= 7190 ~ "Real Estate", 
    .$industry2012 >= 7270 & .$industry2012 <= 7490 ~ "Professional, Scientific, and Technical Services",
    .$industry2012 >= 7570 & .$industry2012 <= 7790 ~ "Management, Administrative and Support, and Waste Management Services",
    .$industry2012 >= 7860 & .$industry2012 <= 7890 ~ "Educational Services",
    .$industry2012 >= 7970 & .$industry2012 <= 8470 ~ "Healthcare and Social Assistance", 
    .$industry2012 >= 8560 & .$industry2012 <= 8590 ~ "Arts, Entertainment, and Recreation", 
    .$industry2012 >= 8660 & .$industry2012 <= 8690 ~ "Accomodation and Food Services", 
    .$industry2012 >= 8770 & .$industry2012 <= 9290 ~ "Other Services", 
    .$industry2012 >= 9370 & .$industry2012 <= 9870 ~ "Public Administration and Active Duty Military", 
    .$industry2012 == 9890 ~ "Armed Forces")))


nlsydata3 <- nlsydata3 %>% 
   mutate(occupation2012 = factor(case_when(
    .$occupation2012 >= 10 & .$occupation2012 <= 430 ~ "Executive & Administrative",
    .$occupation2012 >= 500 & .$occupation2012 <= 950 ~ "Management", 
    .$occupation2012 >= 1000 & .$occupation2012 <= 1240 ~ "Math and Computer Science",
    .$occupation2012 >= 1300 & .$occupation2012 <= 1560 ~ "Engineers & Architects",
    .$occupation2012 >= 1600 & .$occupation2012 <= 1760 ~ "Physical Scientists",
    .$occupation2012 >= 1800 & .$occupation2012 <= 1860 ~ "Social Scientists",
    .$occupation2012 >= 1900 & .$occupation2012 <= 1960 ~ "Life, Physical and Social Science Technicians",
    .$occupation2012 >= 2000 & .$occupation2012 <= 2060 ~ "Counselors & Religious Workers",
    .$occupation2012 >= 2100 & .$occupation2012 <= 2150 ~ "Lawyers, Judges and Legal Support Workers",
    .$occupation2012 >= 2200 & .$occupation2012 <= 2340 ~ "Teachers",
    .$occupation2012 >= 2400 & .$occupation2012 <= 2550 ~ "Education, Training and Library Workers",
    .$occupation2012 >= 2600 & .$occupation2012 <= 2760 ~ "Entertainers and Performers, Sports and Related Workers",
    .$occupation2012 >= 2800 & .$occupation2012 <= 2960 ~ "Media & Communication",
    .$occupation2012 >= 3000 & .$occupation2012 <= 3260 ~ "Health Diagnosing and Treating Practioners",
    .$occupation2012 >= 3300 & .$occupation2012 <= 3650 ~ "Healthcare Technical and Support",
    .$occupation2012 >= 3700 & .$occupation2012 <= 3950 ~ "Protective Services",
    .$occupation2012 >= 4000 & .$occupation2012 <= 4160 ~ "Food Preparation and Serving",
    .$occupation2012 >= 4200 & .$occupation2012 <= 4250 ~ "Cleaning and Building Services", 
    .$occupation2012 >= 4300 & .$occupation2012 <= 4430 ~ "Entertainment Attendants", 
    .$occupation2012 >= 4500 & .$occupation2012 <= 4650 ~ "Personal Care & Service",
    .$occupation2012 >= 4700 & .$occupation2012 <= 4960 ~ "Sales",
    .$occupation2012 >= 5000 & .$occupation2012 <= 5930 ~ "Office and Administrative Support",
    .$occupation2012 >= 6000 & .$occupation2012 <= 6130 ~ "Farming & Fisheries",
    .$occupation2012 >= 6200 & .$occupation2012 <= 6940 ~ "Construction Trade & Extraction",
    .$occupation2012 >= 7000 & .$occupation2012 <= 7620 ~ "Installation, Maintenance and Repairs", 
    .$occupation2012 >= 7700 & .$occupation2012 <= 7750 ~ "Production and Preparation", 
    .$occupation2012 >= 7800 & .$occupation2012 <= 7850 ~ "Food Preparation",
    .$occupation2012 >= 7900 & .$occupation2012 <= 8960 ~ "Setters, Operators and Tenders",
    .$occupation2012 >= 9000 & .$occupation2012 <= 9750 ~ "Transportation and Material Moving",
    .$occupation2012 == 9840 ~ "Armed Forces")))


nlsydata3 <- nlsydata3 %>% 
   mutate(spouse.occupation2012 = factor(case_when(
    .$spouse.occupation2012 >= 10 & .$spouse.occupation2012 <= 430 ~ "Executive & Administrative",
    .$spouse.occupation2012 >= 500 & .$spouse.occupation2012 <= 950 ~ "Management", 
    .$spouse.occupation2012 >= 1000 & .$spouse.occupation2012 <= 1240 ~ "Math and Computer Science",
    .$spouse.occupation2012 >= 1300 & .$spouse.occupation2012 <= 1560 ~ "Engineers & Architects",
    .$spouse.occupation2012 >= 1600 & .$spouse.occupation2012 <= 1760 ~ "Physical Scientists",
    .$spouse.occupation2012 >= 1800 & .$spouse.occupation2012 <= 1860 ~ "Social Scientists",
    .$spouse.occupation2012 >= 1900 & .$spouse.occupation2012 <= 1960 ~ "Life, Physical and Social Science Technicians",
    .$spouse.occupation2012 >= 2000 & .$spouse.occupation2012 <= 2060 ~ "Counselors & Religious Workers",
    .$spouse.occupation2012 >= 2100 & .$spouse.occupation2012 <= 2150 ~ "Lawyers, Judges and Legal Support Workers",
    .$spouse.occupation2012 >= 2200 & .$spouse.occupation2012 <= 2340 ~ "Teachers",
    .$spouse.occupation2012 >= 2400 & .$spouse.occupation2012 <= 2550 ~ "Education, Training and Library Workers",
    .$spouse.occupation2012 >= 2600 & .$spouse.occupation2012 <= 2760 ~ "Entertainers and Performers, Sports and Related Workers",
    .$spouse.occupation2012 >= 2800 & .$spouse.occupation2012 <= 2960 ~ "Media & Communication",
    .$spouse.occupation2012 >= 3000 & .$spouse.occupation2012 <= 3260 ~ "Health Diagnosing and Treating Practioners",
    .$spouse.occupation2012 >= 3300 & .$spouse.occupation2012 <= 3650 ~ "Healthcare Technical and Support",
    .$spouse.occupation2012 >= 3700 & .$spouse.occupation2012 <= 3950 ~ "Protective Services",
    .$spouse.occupation2012 >= 4000 & .$spouse.occupation2012 <= 4160 ~ "Food Preparation and Serving",
    .$spouse.occupation2012 >= 4200 & .$spouse.occupation2012 <= 4250 ~ "Cleaning and Building Services", 
    .$spouse.occupation2012 >= 4300 & .$spouse.occupation2012 <= 4430 ~ "Entertainment Attendants", 
    .$spouse.occupation2012 == 4460 ~ "Funeral Related Occupations", 
    .$spouse.occupation2012 >= 4500 & .$spouse.occupation2012 <= 4650 ~ "Personal Care & Service",
    .$spouse.occupation2012 >= 4700 & .$spouse.occupation2012 <= 4960 ~ "Sales",
    .$spouse.occupation2012 >= 5000 & .$spouse.occupation2012 <= 5930 ~ "Office and Administrative Support",
    .$spouse.occupation2012 >= 6000 & .$spouse.occupation2012 <= 6130 ~ "Farming & Fisheries",
    .$spouse.occupation2012 >= 6200 & .$spouse.occupation2012 <= 6940 ~ "Construction Trade & Extraction",
    .$spouse.occupation2012 >= 7000 & .$spouse.occupation2012 <= 7620 ~ "Installation, Maintenance and Repairs", 
    .$spouse.occupation2012 >= 7700 & .$spouse.occupation2012 <= 7750 ~ "Production and Preparation", 
    .$spouse.occupation2012 >= 7800 & .$spouse.occupation2012 <= 7850 ~ "Food Preparation",
    .$spouse.occupation2012 >= 7900 & .$spouse.occupation2012 <= 8960 ~ "Setters, Operators and Tenders",
    .$spouse.occupation2012 >= 9000 & .$spouse.occupation2012 <= 9750 ~ "Transportation and Material Moving",
    .$spouse.occupation2012 >= 9800 & .$spouse.occupation2012 <= 9830 ~ "Military Specific Operations",
    .$spouse.occupation2012 == 9840 ~ "Armed Forces")))


```

```{r}
# transform and relabel gender and race variables

nlsydata1 <- mutate(nlsydata1, 
                    gender = recode_factor(gender, 
                    `1` = "Male", 
                    `2` = "Female"), 
                    race = recode_factor(race, 
                    `3` = "Other", 
                    `1` = "Hispanic", 
                    `2` = "Black"))
```


```{r}
nlsy.lm <- lm(income2012 ~ gender + race + jobs.held1990, data = nlsydata1)

summary(nlsy.lm)

anova(update(nlsy.lm, .~. - race), nlsy.lm)

nlsy.lm.interact <- update(nlsy.lm, . ~ . + race*gender)

summary(nlsy.lm.interact)

```

```{r}
kable(coef(summary(nlsy.lm)), digits = c(0, 0, 2, 4))
```


**(0)** Data cleaning and data exploration

```{r}

# Then I am going to filter out rows (respondents prior to 2000) that are missing the income values (outcome variable we are looking at)

# Use TOTAL INCOME FROM WAGES AND SALARY IN PAST CALENDAR YEAR (TRUNC) (2012 survey question) as outcome variable

# Create a new variable that is the log of income variable

# Create a variable that labels the top-coded 2% income earners

# Look for variables to drop. Start by looking at variables that are highly covariated with others.


```


```{r}

gendergap.race <- nlsydata1 %>% 
  group_by(race) %>%
  summarize(income.gap = mean(income2012[gender == "Male"], na.rm = TRUE) - mean(income2012[gender == "Female"], na.rm = TRUE), upper = t.test(income2012 ~ gender)$conf.int[1], lower = t.test(income2012 ~ gender)$conf.int[2],  is.significant = as.numeric(t.test(income2012 ~ gender)$p.value < 0.05))

gendergap.race

ggplot(data = gendergap.race, aes(x = race, y = income.gap, fill = race)) + geom_bar(stat = "identity") + xlab("Race") + ylab("Income gap($)") + ggtitle("Income gap between men and women, by race") + guides(fill = FALSE) + geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.1, size = 1) + theme(text = element_text(size = 12))

```

**(1)** Data Summary

```{r}
# Start by discussing the variables of interest and my reasons for choosing these variables.

# Display tabular summaries of means and proportions where appropriate

# tabular summaries should break things down by gender

# Your score for this section will be based on the following criteria:

  #Meaningful variable names, factor variables, and factor level names

  #Insightful graphical and tabular summaries of the data

  #Proper labelling of figure axes and table columns

  # Discussion of the graphical and tabular summaries.

```

**(2)** Methodology

```{r}
# Provide an overview of the approach you took to exploring and analyzing the data

# Use this section as a place to explain the various types of analyses that you tried

# This is where you tell the story of how you got to your main findings.

# You should address at least the following questions:

  #How did you deal with missing values? What impact does your approach have on the interpretation or generalizability of the resulting analysis?

  #How did you deal with topcoded variables? What impact does your approach have on the interpretation or generalizability of the resulting analysis?

  #Did you produce any tables or plots that you thought would reveal interesting trends but didn’t?

  #What relationships did you investigate that don’t appear in your findings section?

  #What’s the analysis that you finally settled on? What income and gender related factors do you investigate in the final analysis?

```

**(3)** Findings

```{r}
# Presentation of your main findings concerning the main problem of income (in)equality between men and women


# You should provide, where appropriate:

  #Tabular summaries (with carefully labelled column headers)

  #Graphical summaries (with carefully labelled axes, titles, and legends)

  #Regression output + interpretation of output + interpretation of coefficients


  #Assessments of statistical significance (output of tests, models, and corresponding p-values)


#As part of your analysis you must run a regression model. When running regressions, you should discuss whether the standard diagnostic plots indicate issues with the model (trends in residuals, variance issues, outliers, etc.). You will not receive full credit for your regression unless you clearly display and discuss the diagnostic plots.

```

**(4)** Discussion

```{r}
# In this section you should summarize your main conclusions.

# You should also discuss potential limitations of your analysis and findings.

#Are there potential confounders that you didn’t control for? Are the models you fit believable?


#You should also address the following question: How much confidence do you have in your analysis? Do you believe your conclusions? Are you confident enough in your analysis and findings to present them to policy makers? (You will not be deducted points for saying that you are unsure of your analysis. This is just something I want you to reflect upon.)

```